// WebsiteTester.VueSPA/src/views/TestDetailsView.vue
<template>
  <h2 class="mt-5">{{ testDetails?.url }}</h2>
  <div class="mt-5">
    <h2>PERFOMANCE</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Url</th>
          <th>Timing</th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="(result, index) in testDetails?.testResults?.slice().sort((a, b) => a.renderTimeMilliseconds - b.renderTimeMilliseconds)" :key="index">
          <td>{{ result.url }}</td>
          <td>{{ result.renderTimeMilliseconds }}</td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="mt-5">
    <h2>URLs NOT FOUND AT WEBSITE</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Url</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(result, index) in testDetails?.testResults?.slice().filter(x => x.isInSitemap && !x.isInWebsite)" :key="index">
          <td>{{ result.url }}</td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="mt-5">
    <h2>URLs NOT FOUND AT SITEMAP</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Url</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(result, index) in testDetails?.testResults?.slice().filter(x => x.isInWebsite && !x.isInSitemap)" :key="index">
          <td>{{ result.url }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script lang="ts">
import type { Link } from '../models/Link';
import { useWebsiteTesterStore } from '../stores/WebsiteTesterStore';
import { ref } from 'vue';

export default {
  name: 'TestDetailsView',
  props: ['id'],
  data() {
    return {
      store: useWebsiteTesterStore(),
      testDetails: ref<Link>()
    }
  },
  methods: {
    fetchDetails() {
      this.store.fetchTestDetails(this.id).then((data) => {
        this.testDetails = data;
      });
    }
  },
  mounted() {
    this.fetchDetails();
  }
}
</script>

// WebsiteTester.React/src/views/TestDetailsView.jsx
import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { useWebsiteTesterStore } from '../stores/WebsiteTesterStore';

function TestDetailsView() {
  const { id } = useParams();
  const store = useWebsiteTesterStore();
  const [testDetails, setTestDetails] = useState(null);

  useEffect(() => {
    fetchDetails();
  }, [id, store]);

  const fetchDetails = () => {
    store.fetchTestDetails(id).then((data) => {
      setTestDetails(data);
    });
  };

  const renderSortedResults = (filterFn) => {
    const filteredResults = testDetails?.testResults?.slice().filter(filterFn);
    const sortedResults = filteredResults?.sort((a, b) => a.renderTimeMilliseconds - b.renderTimeMilliseconds);

    return (
      <table className="table">
        <thead>
          <tr>
            <th>Url</th>
            <th>Timing</th>
          </tr>
        </thead>
        <tbody>
          {sortedResults?.map((result, index) => (
            <tr key={index}>
              <td>{result.url}</td>
              <td>{result.renderTimeMilliseconds}</td>
            </tr>
          ))}
        </tbody>
      </table>
    );
  };

  return (
    <div>
      <h2 className="mt-5">{testDetails?.url}</h2>

      <div className="mt-5">
        <h2>PERFORMANCE</h2>
        {renderSortedResults(() => true)}
      </div>

      <div className="mt-5">
        <h2>URLs NOT FOUND AT WEBSITE</h2>
        {renderSortedResults((x) => x.isInSitemap && !x.isInWebsite)}
      </div>

      <div className="mt-5">
        <h2>URLs NOT FOUND AT SITEMAP</h2>
        {renderSortedResults((x) => x.isInWebsite && !x.isInSitemap)}
      </div>
    </div>
  );
}

export default TestDetailsView;
